using UnityEngine;
using UnityEngine.UI; // 혹은 TMPro

public class UIManager : MonoBehaviour
{
    public GameObject winPanel;
    public Button btnNext;

    private void Start()
    {
        btnNext.onClick.AddListener(OnClickNextLevel);
    }

    public void ShowWinUI()
    {
        winPanel.SetActive(true);
        // 여기에 팡파레 파티클이나 효과음을 재생하면 좋습니다.
    }

    public void HideWinUI()
    {
        winPanel.SetActive(false);
    }

    // 버튼에 연결할 함수
    public void OnClickNextLevel()
    {
        winPanel.SetActive(false);
        GameManager.Instance.LoadNextLevel();
    }
}